apiVersion: v1
kind: Secret
metadata:
  name: dockercred
  namespace: sample-app
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJzYXRpc2hrLmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJaRzlqYTJWeVkzSmxaRHBUWVhScGMyZ3hNak09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
